#! /bin/bash
#
# Usage: "run path/to/scanner destdir"
#

scanner=$1
destdir=$2

for src in `ls samples/*.qk`; do
   srcname=`basename ${src}`
   echo "Scanning ${src}, producing ${destname}/${srcname}.out"
   ${scanner} ${src} >${destdir}/${srcname}.out 2>${destdir}/${srcname}.err
done
